#ifndef QUESTION_H
#define QUESTION_H
#include "system.h"

sc_addr CLASS_QUESTION;
sc_addr CLASS_QUESTION_INITIATED;

sc_addr CLASS_QUESTION_ALL_OUTPUT_CONST_POS_ARC;
sc_addr CLASS_QUESTION_ALL_INPUT_CONST_POS_ARC;
sc_addr CLASS_QUESTION_FULL_SEMANTIC_NEIGHBOURHOOD;

sc_addr NREL_ANSWER;

void init_questions();

#endif // QUESTION_H
